### ISSUE TITLE
Pages reload continuously in Safari

### ISSUE THREAD

**Issue by rgerkin** [OpenSourceBrain/OSB_Status#6]
On OSX, the Safari browser continuously reloads [this page](http://www.opensourcebrain.org/projects/thalamocortical) (and possibly others).  This does not occur in Chrome.

**Comment by mattearnshaw** [comment]
@rgerkin thanks – this should be fixed now (may require clearing cache), can you confirm?

**Comment by rgerkin** [comment]
Fixed.
